// Todos
export const GET_TODOS = 'GET_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const ADD_SUBTODO = 'ADD_SUBTODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_SUBTODO = 'DELETE_SUBTODO';
export const SET_CURRENT = 'SET_CURRENT';
export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_SUBTODO = 'UPDATE_SUBTODO';
export const FILTER_TODOS = 'FILTER_TODOS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SORT_TODOS_PRIORITY = 'SORT_TODOS_PRIORITY';
export const SORT_TODOS_DEADLINE = 'SORT_TODOS_DEADLINE';
export const SORT_TODOS_ALPHABETICAL = 'SORT_TODOS_ALPHABETICAL';

// Pomodoro Timer
export const UPDATE_POMODORO_TIME = 'UPDATE_POMODORO_TIME';
export const UPDATE_BREAK_TIME = 'UPDATE_BREAK_TIME';
export const UPDATE_LONG_BREAK_TIME = 'UPDATE_LONG_BREAK_TIME';
export const GET_POMODORO = 'GET_POMODORO';
export const RESET_POMODORO = 'RESET_POMODORO';

// Flashcards
export const GET_FLASHCARDS = 'GET_FLASHCARDS';
export const ADD_FLASHCARD = 'ADD_FLASHCARD';
export const UPDATE_FLASHCARD = 'UPDATE_FLASHCARD';
export const DELETE_FLASHCARD = 'DELETE_FLASHCARD';
export const SET_CURRENT_FLASHCARD = 'SET_CURRENT_FLASHCARD';
export const CLEAR_CURRENT_FLASHCARD = 'CLEAR_CURRENT_FLASHCARD';
export const FILTER_FLASHCARDS = 'FILTER_FLASHCARDS';
export const CLEAR_FILTER_FLASHCARDS = 'CLEAR_FILTER_FLASHCARDS';
export const SET_FLASHCARD_ACTIVE = 'SET_FLASHCARD_ACTIVE';
export const SET_FLASHCARD_INACTIVE = 'SET_FLASHCARD_INACTIVE';
export const SET_ALL_FLASHCARDS_ACTIVE = 'SET_ALL_FLASHCARDS_ACTIVE';

// Events
export const GET_EVENTS = 'GET_EVENTS';
export const ADD_EVENT = 'ADD_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const CLEAR_CURRENT_EVENT = 'CLEAR_CURRENT_EVENT';
