// Todos
export const GET_TODOS = "GET_TODOS";
export const GET_SUBTODOS = "GET_SUBTODOS";
export const ADD_TODO = "ADD_TODO";
export const ADD_SUBTODO = "ADD_SUBTODO";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_SUBTODO = "DELETE_SUBTODO";
export const SET_CURRENT = "SET_CURRENT";
export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_SUBTODO = "UPDATE_SUBTODO";
export const FILTER_TODOS = "FILTER_TODOS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SORT_TODOS_PRIORITY = "SORT_TODOS_PRIORITY";
export const SORT_TODOS_DEADLINE = "SORT_TODOS_DEADLINE";
export const SORT_TODOS_ALPHABETICAL = "SORT_TODOS_ALPHABETICAL";
export const TODO_ERROR = "TODO_ERROR";
export const SUBTODO_ERROR = "SUBTODO_ERROR";

// Pomodoro Timer
export const GET_POMODORO_SETTINGS = "GET_POMODORO_SETTINGS";
export const ADD_POMODORO_SETTINGS = "ADD_POMODORO_SETTINGS";
export const UPDATE_POMODORO_SETTINGS = "UPDATE_POMODORO_SETTINGS";
export const POMODORO_ERROR = "POMODORO_ERROR";

// Flashcards
export const GET_FLASHCARDS = "GET_FLASHCARDS";
export const ADD_FLASHCARD = "ADD_FLASHCARD";
export const UPDATE_FLASHCARD = "UPDATE_FLASHCARD";
export const DELETE_FLASHCARD = "DELETE_FLASHCARD";
export const SET_CURRENT_FLASHCARD = "SET_CURRENT_FLASHCARD";
export const CLEAR_CURRENT_FLASHCARD = "CLEAR_CURRENT_FLASHCARD";
export const FILTER_FLASHCARDS = "FILTER_FLASHCARDS";
export const CLEAR_FILTER_FLASHCARDS = "CLEAR_FILTER_FLASHCARDS";
export const FLASHCARD_ERROR = "FLASHCARD_ERROR";

// Events
export const GET_EVENTS = "GET_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const CLEAR_CURRENT_EVENT = "CLEAR_CURRENT_EVENT";
export const EVENT_ERROR = "EVENT_ERROR";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
